[tool.uv.workspace]
members = [
  "apps/ls-api",
  "apps/heater-api",
  "packages/api-client/src/python/lgg",
  "packages/api-client/src/python/simulator",
]

[dependency-groups]
dev = [
    "pip-licenses>=5.5.0",
    "requests>=2.32.5",
]
