openapi: 3.0.3
info:
  title: Simulator (LT Capstone)
  description: Simulator for Foam Box, works as stub/mocks for lgg-api and heater-api.
  version: 0.1.0
tags:
  - name: Simulator
    description: Endpoints related to simulator functionalities
paths:
  /temperature/{channel}:
    get:
      tags:
        - Simulator
      operationId: getSimulatorTemperature
      summary: Get Simulator Temperature
      description: Retrieve simulated temperature for a given channel
      parameters:
        - name: channel
          in: path
          required: true
          schema:
            description: Lakeshore Channel number to retrieve the simulated temperature for
            type: number
      responses:
        "200":
          description: Response for status 200
          content:
            application/json:
              schema:
                type: object
                properties:
                  temperature:
                    description: Simulated temperature in Kelvin
                    type: number
                  _celcius:
                    description: Simulated temperature in Celsius (For testing purposes)
                    type: number
                required:
                  - temperature
                  - _celcius
        "404":
          description: Response for status 404
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    example: Channel not found
                    type: string
                required:
                  - error
  /heater/{pin}:
    post:
      tags:
        - Simulator
      operationId: setHeaterOutput
      summary: Set Heater Output
      description: Set the heater output level for a given GPIO pin
      parameters:
        - name: pin
          in: path
          required: true
          schema:
            description: GPIO pin number associated with the heater
            type: number
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                value:
                  description: Heater output level (0.0 to 1.0)
                  minimum: 0
                  maximum: 1
                  type: number
              required:
                - value
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                value:
                  description: Heater output level (0.0 to 1.0)
                  minimum: 0
                  maximum: 1
                  type: number
              required:
                - value
          multipart/form-data:
            schema:
              type: object
              properties:
                value:
                  description: Heater output level (0.0 to 1.0)
                  minimum: 0
                  maximum: 1
                  type: number
              required:
                - value
      responses:
        "200":
          description: Response for status 200
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    default: true
                    type: boolean
                required:
                  - success
        "404":
          description: Response for status 404
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    example: Pin not found
                    type: string
                required:
                  - error
components:
  schemas: {}
